#!/bin/bash


# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

rm *.png &>/dev/null
rm *.pdf &>/dev/null

cd coarse
cleanCase
rm *.plt &>/dev/null
cd -

cd medium
cleanCase
rm *.plt &>/dev/null
cd -

cd fine
cleanCase
rm *.plt &>/dev/null
cd -
