#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application="dgLaplacianFoam"

\cp -f blockMeshDict constant/polyMesh/blockMeshDict
runApplication blockMesh
#runApplication $application

#runApplication decomposePar -cellDist
#runApplication decomposeSets -writeEmptySets
#runParallel $application 3
