#ifndef dgCFD_H
#define dgCFD_H

#include "parRun.H"

#include "objectRegistry.H"
#include "foamTime.H"
#include "dgMesh.H"
#include "dgPrimitiveFields.H"
#include "cellFields.H"
#include "dgc.H"
#include "dgMatrices.H"
//#include "dgPolynomials.H"
 #include "dgm.H"
// #include "linear.H"
// #include "uniformDimensionedFields.H"
// #include "calculatedDgPatchFields.H"
// #include "fixedValueDgPatchFields.H"
// #include "adjustPhi.H"
// #include "findRefCell.H"
#include "mathematicalConstants.H"

#include "OSspecific.H"
#include "argList.H"
#include "timeSelector.H"

#ifndef namespaceFoam
#define namespaceFoam
    using namespace Foam;
#endif

#endif
