variables:
  GIT_DEPTH: 10
  FOAM_DG_ROOT: /home/gitlab-runner/builds/4AssrEmF/0/bosss1/foam-dg/

Integration:
  rules:
    - if: $CI_MERGE_REQUEST_ID 
  trigger:
    include:
      - local: integration.yml
    strategy: depend

image: python:3.6

send-snapshot:
  rules:
    - if: $CI_COMMIT_TAG =~ /^v?[0-9]+\.[0-9]+/
  script:
    - pip3 install gitlab2zenodo
    - git archive --format zip --output ${CI_COMMIT_TAG#v}.zip ${CI_COMMIT_TAG}
    - /home/gitlab-runner/.local/bin/g2z-send -t $zenodo_token -s -m .zenodo.json ${CI_COMMIT_TAG#v}.zip
  tags:
    - linux
