workflow:
  rules:
    - when: always
    #- if: $CI_MERGE_REQUEST_ID               # Execute jobs in merge request context
    #- if: $CI_COMMIT_BRANCH == 'master'    # Execute jobs when a new commit is pushed to master branch

stages:
  - build
  - test

include: 
  - local: release.yml
