#!/bin/sh

cd ../../src/
./Allwmake
cd -

#generate mesh
blockMesh

cp 0/C.orig 0/C
cp 0/U.orig 0/U

#remove bug in of 4ext
find . -name "pd" -type f | xargs sed -i -e '/rAU/d'

./setFields.sh

CahnHilliardFoam



