#!/bin/sh
set -x

rm -r ./discontinuousGalerkin/lnInclude
wmakeLnInclude discontinuousGalerkin
# wmakeLnInclude CahnHilliardFoam

wmake libso discontinuousGalerkin

# wmake testDg
# wmake testDgField

# wmake dgLaplacianFoam
wmake CahnHilliardFoam
# wmake dgConvectionFoam
# wmake dgScalarTransport
# wmake fvTransform
# wmake fvPointTransform
