#!/bin/sh
set -x

# export FOAM_USER_LIBBIN=/home/gitlab-runner/foam/administrator-4.1/lib/linux64GccDPInt32Opt

rm -r ./discontinuousGalerkin/lnInclude
wmakeLnInclude discontinuousGalerkin
# wmakeLnInclude CahnHilliardFoam

wmake libso discontinuousGalerkin

# wmake testDg
# wmake testDgField

# wmake dgLaplacianFoam
wmake CahnHilliardFoam
# wmake dgConvectionFoam
# wmake dgScalarTransport
# wmake fvTransform
# wmake fvPointTransform
